all:
	-@quarto render

clean:
	-rm -rf _output
	-rm -rf output
	-rm -f arch-pc--lab02--report.pdf arch-pc--lab02--report.docx
	-rm -f *.aux *.log *.lof *.lot *.toc *.bcf *.tex

cleanall: clean
	-rm -rf .quarto
